version: "3.8"
services:
  ### Postgres Database ###
  postgres:
    image: postgres:10.4
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  ### API Spring Boot ###
  api:
    build:
      dockerfile: Dockerfile
      context: ./transactions-management/
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:5432/db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    ports:
      - "8080:3000"
